# Note that the following stanza uses CircleCI 2.1 to make use of a Reusable Executor
# This allows defining a docker image to reuse across jobs.
# visit https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors to learn more.

version: 2.1

executors:
  the-executor:
    docker:
      - image: cimg/node:22.11.0
    working_directory: ~/mediajel-tracker

orbs:
  aws-s3: circleci/aws-s3@2.0.0
  aws-cloudfront: topmonks/aws-cloudfront@1.0.0
jobs:
  build-staging:
    executor: the-executor
    steps:
      - checkout
      - run:
          name: Install project dependencies
          command: yarn install
      - run:
          name: type checking
          command: yarn tsc --noEmit
        #   TODO: UNCOMMENT LATER
      - run:
          name: Cypress Install
          command: sudo apt-get update && sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run:
          name: cypress tests
          command: npm run test
      - run:
          name: Build
          command: npm run deploy
      - aws-s3/sync:
          from: dist/
          to: "s3://mediajel-tracker-staging"
          arguments: --cache-control "max-age=2628288"
      - aws-cloudfront/invalidate:
          distribution_id: E1ZEPT1NM5152K
          paths: /*

  build-main:
    executor: the-executor
    steps:
      - checkout
      - run:
          name: Install project dependencies
          command: yarn install
  
      - run:
          name: type checking
          command: yarn tsc --noEmit
      # - run:
      #     name: Cypress Install
      #     command: sudo apt-get update && sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      # - run:
      #     name: cypress tests
      #     command: npm run test
      - run:
          name: Build
          command: yarn deploy
      - aws-s3/sync:
          from: dist/
          to: "s3://mediajel-tracker-production"
          arguments: --cache-control "max-age=2628288"
      - aws-cloudfront/invalidate:
          distribution_id: E3NZWAOF5B6J2O
          paths: /*    
      - aws-cloudfront/invalidate:
          distribution_id: E3FT67SI37G1ZH
          paths: /*
      - aws-cloudfront/invalidate:
          distribution_id: EQGTP3X7S8LMI
          paths: /*
      - aws-cloudfront/invalidate:
          distribution_id: EFJHMMZDNURYT
          paths: /*
      - aws-cloudfront/invalidate:
          distribution_id: E3FT67SI37G1ZH
          paths: /*
      - aws-cloudfront/invalidate:
          distribution_id: EQGTP3X7S8LMI
          paths: /*
      - aws-cloudfront/invalidate:
          distribution_id: E39XLCEMWS6VO1
          paths: /*
      - aws-cloudfront/invalidate:
          distribution_id: E270PRY60O4B3Y
          paths: /*
      - aws-cloudfront/invalidate:
          distribution_id: ELFZ8CP0408WK
          paths: /*
      - run:
          name: Run Tracker
          command: npm run tracker:generate-environments

workflows:
  version: 2
  build:
    jobs:
      - build-staging:
          context: STAGING
          filters:
            branches:
              only: staging
      - build-main:
          context: PRODUCTION
          filters:
            branches:
              only: main
